#!/usr/bin/env python3
# encoding: utf8
#
# HID Download Tool
#
# Copyright (c) BekenCorp. (chunjian.tian@bekencorp.com).  All rights reserved.
#
# This software may be distributed under the terms of the BSD license.
# See README for more details.

import sys
import os
import argparse
from bkutils import UartDownloader
import hid
import threading

# parse commandline arguments
def parse_args():
    description = '''Beken Uart Downloader.'''
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('-d', '--device',
                        default='/dev/ttyUSB0',
                        help="Uart device, default /dev/ttyUSB0")
    parser.add_argument('-s', '--startaddr', type=lambda  x: int(x, 16),
                        default=0x11000,
                        help="burn flash address, defaults to 0x11000")
    parser.add_argument('-b', '--baudrate', type=int,
                        default=2000000,
                        help="burn uart baudrate, defaults to 2000000")
    parser.add_argument('-u', '--unprotect', action="store_true",
                        help="unprotect flash first, used by BK7231N")
    parser.add_argument('filename',
                        help='specify file_crc.bin')
    args = parser.parse_args()

    return args

args = parse_args()

downloader = UartDownloader(args.device, args.baudrate, args.unprotect)
downloader.programm(args.filename, args.startaddr)
